Edit & delete comments BE
S7012MY/CodeWell pull request #100
Opened 2020-12-09 11:14 UTC by dayanamdr

2020-12-09 19:29 UTC, andreisamoila74 requested changes

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
>    $if_login->post('/api/comment/add')->name('on_comment_add')
also, let's update the name of the route

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($comment_request->{id}) {
```suggestion
  if ($comment_request->{id} && $code) {
```

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $error .= get_error('permission_denied') unless $user;
try to write this more clear

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    my $comment_id = validate_comment_id_existence($self,
this validation should go first

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  $comment_object->delete if $success;
you already have the $comment object defined above

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    });
also check that the comment still exists in the database

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +subtest 'Can not delete a comment for an inexistent code_id' => sub {
```suggestion
subtest 'Can not delete a comment for invalid code Id' => sub {
```

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +subtest 'Can not delete a comment for an inexistent comment id' => sub {
```suggestion
subtest 'Can not delete a comment for an invalid comment id' => sub {
```

2020-12-09 19:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +subtest 'Can not edit a comment for an inexistent comment id' => sub {
this should go first when testing the edit part

2020-12-11 09:22 UTC, andreisamoila74 requested changes

2020-12-11 09:22 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
> +    ->to('comment#on_edit_or_add');
the route was fine to be called /api/comment/add, by the name of the route, I meant: 
```->name('on_comment_edit_or_add')```

2020-12-11 09:22 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    my $comment_id = validate_comment_id_existence($self,
here should be $comment, because the function 'validate_comment_id_existence' returns a comment objects if the id received as parameter is defined

2020-12-11 09:22 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $error .= get_error('permission_denied') unless $user;
```suggestion
    $error .= get_error('permission_denied') unless validate_comment_edit_permission($self,
      $comment_request->{user_id})
```
```suggestion
    my $user = validate_comment_edit_permission($self,
      $comment_request->{user_id});
    $error .= get_error('permission_denied') unless $user;
```
```suggestion
    my $user = validate_comment_edit_permission($self,
      $comment_request->{user_id});
    $error .= get_error('permission_denied') unless $user;
```
```suggestion
    my $user = validate_comment_edit_permission($self,
      $comment_request->{user_id});
    $error .= get_error('permission_denied') unless $user;
```

2020-12-11 09:24 UTC, andreisamoila74 requested changes

2020-12-11 09:24 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    ->find({ body => 'Sixth comment' });
leave some comments about these comments, is difficult to follow this test

2020-12-11 14:48 UTC, andreisamoila74 requested changes

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $error .= get_error('invalid_comment_id') unless $comment;
can we write like this?
```suggestion
    $error .= get_error('invalid_comment_id') unless validate_comment_id_existence($self,
      $comment_request->{id});
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    });
this change is not relevant

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $comment->user_id,
```suggestion
      user_id => $comment->user_id,
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +          user_id =>  $fourth_comment->user_id,
```suggestion
          user_id => $fourth_comment->user_id,
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +          user_id =>  $fifth_comment->user_id,
```suggestion
          user_id => $fifth_comment->user_id,
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $second_comment->user_id,
```suggestion
      user_id => $second_comment->user_id,
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $third_comment->user_id,
```suggestion
      user_id => $third_comment->user_id,
```

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $third_comment->user_id,
please be more carefully at this kind of mistakes

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $second_comment->user_id,
same here

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      user_id =>  $third_comment->user_id,
:(

2020-12-11 14:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +  ok $t->app->db->resultset('Comment')->find({ id => $third_comment->id })
we have "by_id" function in the comment resultset

2020-12-12 16:07 UTC, S7012MY commented on codewellBe/lib/codewellBE.pm
> +  $if_login->post('/api/comment/add')->name('on_comment_edit_or_add')
on_comment_add_edit

2020-12-12 16:07 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +sub on_edit_or_add {
same here

2020-12-12 16:08 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $comment_request->{id} ? $comment_request->{user_id} : $self->session('id'),
you can use the `//` operator

2020-12-12 16:09 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $self->session('role') eq 'ADMIN';
we should also let the author delete his comment for now

2020-12-12 16:10 UTC, S7012MY commented on codewellBe/t/Controller/comment.t
> +subtest 'An admin can delete other user\'s comment' => sub {
why is this test so huuuuuuge?

2020-12-13 18:49 UTC, S7012MY approved these changes

2020-12-14 18:10 UTC, andreisamoila74 requested changes

2020-12-14 18:10 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
> +  $if_login->post('/api/comment/edit')->name('on_comment_edit')
let's place this route under the add route

2020-12-14 18:10 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +sub on_edit {
let's place this right after the on_add function

2020-12-14 18:10 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  }
```suggestion
    $error = get_error('permission_denied') unless !defined $comment
      && validate_comment_delete_edit_permission($self, $comment->user_id);
```
please check if this work properly

2020-12-14 18:10 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +sub validate_comment_delete_edit_permission {
I would call it validate_comment_edit_or_delete permission

2020-12-14 18:10 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +subtest 'Can not edit with an invalid body' => sub {
```suggestion
subtest 'Can not edit a comment with an invalid body' => sub {
```

2020-12-15 19:58 UTC, andreisamoila74 requested changes

2020-12-15 19:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $error = get_error('invalid_comment_id') unless $comment;
indentation😁😁

2020-12-15 19:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    !validate_comment_edit_or_delete_permission($self, $comment->user_id);
```suggestion
  $error = get_error('permission_denied') if $comment
    && !validate_comment_edit_or_delete_permission($self, $comment->user_id);
```

2020-12-15 19:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    $error = get_error('invalid_comment_id') unless $comment;
indentation

2020-12-15 19:58 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +};
why are these lines green?

2020-12-15 19:58 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +};
they shouldn't be considered as new lines

2020-12-16 09:48 UTC, dayanamdr commented on codewellBe/t/Controller/comment.t
> +};
the indentation was bad and I corrected it

2020-12-17 20:23 UTC, S7012MY approved these changes

2020-12-18 11:51 UTC, andreisamoila74 approved these changes

2020-12-18 11:51 UTC, merged