Refactor CommentsList component
S7012MY/CodeWell pull request #101
Opened 2020-12-10 10:14 UTC by andreisamoila74

2020-12-10 17:33 UTC, S7012MY requested changes

2020-12-10 17:33 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +  *   - toggleReplyBoxVisibility - function that updates the visibility
why aren't we doing this in AddComment? This way only this component handles its visibility

2020-12-11 10:41 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/Add.js
> +  *   - toggleReplyBoxVisibility - function that updates the visibility
because we need to toggle the AddComment component visibility with the plus button on a code line

2020-12-11 13:55 UTC, S7012MY requested changes

2020-12-11 13:55 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +    {(props.isVisible && props.lineNumber) || (props.isVisible === undefined)
if it's undefined means it's not visible. Don't use reverse logic

2020-12-11 13:55 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +                ? <Button id={"cancel-add-reply-comment-" + props.parentCommentId}
why do we have 2 buttons that do the same thing?

2020-12-11 15:41 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/Add.js
> +                ? <Button id={"cancel-add-reply-comment-" + props.parentCommentId}
because each button has a different action and id. also each button has a different rendering condition. if I merge the conditional rendering logic, will be not clear enough what that button does.

2020-12-12 10:43 UTC, S7012MY requested changes

2020-12-12 10:43 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +  *   - id - id of the code
codeId

2020-12-12 10:43 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +  *   - commentIndex - index of the comment in the comments list
Briefly explain why is this needed

2020-12-17 20:32 UTC, S7012MY requested changes
We need some tests for commentList as well (based on the visitility params to have elements appear or not)

2020-12-17 20:32 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> + *   - visibility - 1 if the add comment section is visible, 0 otherwise
for example isVisible

2020-12-17 20:32 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +        setVisibility(0);
we should only make this component invisible when the cancel button is pressed. Imagine the case when we want to write multiple ideas for one line

2020-12-17 20:32 UTC, S7012MY commented on codewell-fe/src/__tests__/Comment/Add.test.js
tests for this component need to be rewritten and be more granular

2020-12-21 11:18 UTC, S7012MY approved these changes

2020-12-21 11:18 UTC, S7012MY commented on codewell-fe/src/Components/Comment/List.js
> + *   - lineNumber - code line number; can be undefined
is this for testing purposes only? If so, add this in the comment

2020-12-21 11:29 UTC, merged