[WIP] Add comment back end
S7012MY/CodeWell pull request #20
Opened 2020-07-27 22:12 UTC by S7012MY

2020-08-11 08:01 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Code.pm
> +package codewellBE::Helper::Validator::Code;
g

2020-08-11 08:01 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Code.pm
> +
f

2020-08-23 19:17 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Code.pm
> -sub view {
what?

2020-08-23 19:17 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Code.pm
> -sub view {
what?

2020-08-26 12:58 UTC, andreisamoila74 requested changes
please rethink testing strategy, there too many unnecessary cases

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    unless validate_comment_body($comment_request->{body});
newline here

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +        $error .= 'Code id does not match with parent code id. '
```suggestion
        $error .= 'Code id does not match with the parent comment code id. '
```

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +      $code->source_code, $comment_request->{line_number})) {
you could place the first parameter, $code->source_code, on the line above

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  }
newline here

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if (defined $comment_request->{line_number}) {
```suggestion
  if ($comment_request->{line_number}) {
```

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +        if (defined $comment_request->{parent_comment_id}) {
```suggestion
        if ($comment_request->{parent_comment_id}) {
```

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +sub validate_parent_code_id {
let's call it 'validate_parent_comment_code_id'

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $controller->db->resultset('Comment')->by_id($id)->code_id eq $code_id;
this line is too wide

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +sub validate_parent_line_number {
validate_parent_comment_line_number

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  my $parent_line_number = $controller->db->resultset('Comment')->by_id($id);
bad name, call it 'parent_comment'

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/t/lib/TestHelper.pm
> +  create_code
alph

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Invalid everything
```suggestion
    # All fields invalid
```

2020-08-26 12:58 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +  my $normal_comment_id = $t->app->db->resultset('Comment')
bad name

2020-08-26 19:09 UTC, S7012MY commented on codewellBe/lib/codewellBE/Helper/Validator/Code.pm
> +  return $line_number > 0 && $line_number <= scalar split('\n', $source_code);
```suggestion
  return 0 < $line_number && $line_number <= scalar split('\n', $source_code);
```

2020-08-27 08:52 UTC, andreisamoila74 requested changes

2020-08-27 08:52 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +        $error .= 'Code id does not match with the parent comment code id. '
```suggestion
        $error .= 'Comment code id does not match with the parent comment code id. '
```

2020-08-27 08:52 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Normal comment
it's not clear enough what is a normal comment

2020-08-27 08:52 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Without body
use clear description

2020-08-27 08:52 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Invalid line number
these tests have been already checked before

2020-08-27 11:21 UTC, andreisamoila74 requested changes
+ update tests

2020-08-27 11:21 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  my ($controller, $code_id, $id) = @_;
let's call the parameter $id => $parent_comment_id

2020-08-27 11:21 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $parent_comment eq $code_id;
```suggestion
  my $parent_comment = $controller->db->resultset('Comment')->by_id($id);
  return $parent_comment->code_id eq $code_id;
```

2020-08-27 11:21 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  my ($controller, $id, $line_number) = @_;
same here for the id

2020-08-27 11:21 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +      $error .= 'Comment parent id does not exist. ';
```suggestion
      $error .= 'Parent comment id does not exist. ';
```

2020-08-27 11:21 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  $error .= 'Comment body cannot be empty. '
let's check all this only if the $code is defined

2020-08-27 19:32 UTC, andreisamoila74 requested changes
it's important to have a clear description of the tests, and in general it's important to clearly describe what are you trying to achieve

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code = validate_code_existence($self, $comment_request->{code_id})) {
???

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # General comment on the code
parent comment, not general

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Invalid code id with content
just say what is invalid and what is valid

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Valid code id without content
valid code id with invalid comment body

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Add reply to comment
"Add reply to parent comment"

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Line comment
??

2020-08-27 19:32 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Add line comment
??

2020-08-27 19:48 UTC, alex0popa commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code = validate_code_existence($self, $comment_request->{code_id})) {
I need the contents of the code to check the line number, line  33

2020-08-27 19:55 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code = validate_code_existence($self, $comment_request->{code_id})) {
get the $code on a separate line, it's more elegant like this

2020-08-27 19:56 UTC, alex0popa commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code = validate_code_existence($self, $comment_request->{code_id})) {
got it, thanks

2020-08-29 08:29 UTC, andreisamoila74 requested changes

2020-08-29 08:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Valide code id with valid comment body and invalid parent comment id
valide?

2020-08-29 08:29 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +
there is not clear enough when you are testing comments which are on code lines, and comments which aren't

2020-08-29 10:28 UTC, alex0popa commented on codewellBe/t/Controller/comment.t
> +
"Parent comment on code line."
"Reply to parent comment on code line."
It is more appropriate?

2020-08-30 08:54 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +
yes

2020-08-30 09:29 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    }
```suggestion
  $error .= 'Comment code id does not exist. ' unless $code.

  if ($code) {
    $error .= 'Comment body cannot be empty. '
      unless validate_comment_body($comment_request->{body});

    if ($comment_request->{parent_comment_id}) {
      my $comment = validate_comment_id_existence($self,
        $comment_request->{parent_comment_id});
      $error .= 'Parent comment id does not exist. ' unless $comment;

      if ($comment) {
        $error .= 'Comment code id does not match with the parent comment '
          . 'code id. ' unless validate_parent_comment_code_id($self,
            $comment_request->{parent_comment_id},
              comment_request->{code_id});
      }
    }
```

2020-08-31 07:47 UTC, andreisamoila74 requested changes

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  my ($success, $error, $parent_comment) = (1, '');
don't declare $parent_comment here

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +
you don't need this empty line

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +      my $valid_line_number = validate_line_number($code->source_code,
my $is_line_number_valid

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +        if $valid_line_number && $parent_comment &&
the conditions are not clear enough, let's use an if statement here: if ($parent_comment) { ... }

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $parent_comment->code_id eq $code->id;
let's use the previous version of this function, it's probably to use it again in the future

2020-08-31 07:47 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $parent_comment->line_number == $line_number;
same here

2020-08-31 12:31 UTC, andreisamoila74 requested changes

2020-08-31 12:31 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +          $comment_request->{code_id});
indent this

2020-08-31 12:31 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Add comment
this test is irrelevant because above you are doing a request where you create the same comment

2020-08-31 12:31 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    # Add parent comment on code line
irrelevant test because of the line 139 request

2020-08-31 12:31 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +      comment_request => {
we don't need this one

2020-09-04 11:09 UTC, andreisamoila74 requested changes

2020-09-04 11:09 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +      $error .= get_error('wrong_comment_parent_code_id') if $parent_comment
'invalid_comment_parent_code_id'

2020-09-04 11:09 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  wrong_line => 'Line number does not match with the parent line number. '
bad name here, you have both invalid_line and wrong_line, so is not clear enough

2020-09-04 11:09 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +our @EXPORT_OK = @EXPORT;
do you still need this? :)

2020-09-05 11:46 UTC, andreisamoila74 requested changes

2020-09-05 11:46 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +use codewellBE::Helper::Errors;
this should be declared above the helpers

2020-09-05 11:46 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  $error .= get_error('invalid_code_id')unless $code;
please take a look at this line ..

2020-09-05 19:55 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +use codewellBE::Helper::Validator::Comment qw(
why not import everything

2020-09-05 19:55 UTC, S7012MY commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  empty_body => 'Comment body cannot be empty. ',
if you want to make this general I'd rename this to empty_comment_body

2020-09-05 19:55 UTC, S7012MY commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  invalid_line => 'Invalid line number. ',
invalid_line_number

2020-09-05 19:55 UTC, S7012MY commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $controller->db->resultset('Comment')->find({ id => $id });
we already have a function that does the same thing in the ResultSet

2020-09-05 21:24 UTC, alex0popa commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +use codewellBE::Helper::Validator::Comment qw(
I imported everything. If there were other functions I didn't need, I wouldn't have imported them.
I use EXPORT_OK to export functions and I need to specify what I want to use from that file, otherwise it will not be available.

2020-09-05 21:24 UTC, alex0popa commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code) {
If there is no code, we already receive an error and the other checks are useless.

2020-09-05 21:24 UTC, alex0popa commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  empty_body => 'Comment body cannot be empty. ',
Ok

2020-09-05 21:24 UTC, alex0popa commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  invalid_line => 'Invalid line number. ',
Ok

2020-09-05 21:24 UTC, alex0popa commented on codewellBe/lib/codewellBE/Helper/Validator/Comment.pm
> +  return $controller->db->resultset('Comment')->find({ id => $id });
You are right!

2020-09-07 10:25 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +use codewellBE::Helper::Validator::Comment qw(
what I meant was for you to just do `use codewellBE::Helper::Validator::Comment`

2020-09-07 10:25 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  if ($code) {
then you can just return instead of using if, but what's the harm in doing the other checks?

2020-09-08 12:48 UTC, S7012MY reviewed
Approved

2020-09-08 12:52 UTC, andreisamoila74 approved these changes

2020-09-08 17:52 UTC, merged