View comments BE
S7012MY/CodeWell pull request #45
Opened 2020-09-29 18:05 UTC by dayanamdr

2020-09-29 19:48 UTC, andreisamoila74 requested changes

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
> +  $if_login->get('/api/comment/view/:code_id')->name('on_comment_view')
/api/comments/:code_id

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +sub view_comments {
comments

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  $error .= 'Code id does not exist.' unless $code;
we have a hash that contains all the errors, check Helper/Errors.pm

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +    comments => $comments });
```suggestion
  $self->render(json => { 
    success => $success, 
    error => $error,
    comments => $comments 
  });
```

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Comment.pm
> +sub get_comments {
get_code_parent_comments

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Comment.pm
> +  ];
this don't need to be on a new line

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Schema/ResultSet/Comment.pm
> +  return shift->search({ code_id => $code_id });
```suggestion
  return shift->search({ code_id => pop });
```

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +my $code_id = create_code($t, "Hello World!")->id;
there is already a created code

2020-09-29 19:48 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +subtest 'Can view comments' => sub {
all these 3 subtests can be in a single one, called 'Code comments'

2020-09-30 14:40 UTC, S7012MY requested changes

2020-09-30 14:40 UTC, S7012MY commented on codewellBe/lib/codewellBE/Controller/Comment.pm
> +  $error .= get_error("invalid_code_id") unless $code;
use single ticks (') for constant strings

2020-09-30 14:40 UTC, S7012MY commented on codewellBe/lib/codewellBE/Helper/Comment.pm
> +      ->by_code_id($code_id)->all ];
filter first by code_id and then order them

2020-09-30 14:40 UTC, S7012MY commented on codewellBe/t/Controller/comment.t
> +      comments => \@ok_comment
this shouldn't be an array ref but an json array containing the comments.
Also test with multiple comments so the sorting is also tested

2020-10-01 09:44 UTC, andreisamoila74 requested changes

2020-10-01 09:44 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
> +  $if_login->get('/api/comments/:code_id')->name('on_comment_view')
on_comments_view

2020-10-01 09:44 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Schema/ResultSet/Comment.pm
> +  my ($self, $code_id) = @_;
you don't need this line anymore, that's why you used shift and pop

2020-10-01 09:44 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +  $t->get_ok("/api/comments/inexistent")->status_is(200)
```suggestion
  $t->get_ok('/api/comments/inexistent')->status_is(200)
```

2020-10-01 09:44 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +  my $second_comment = create_comment($t, "Second comment", $code_id);
'' instead of ""

2020-10-01 09:44 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    });
```suggestion
  my @ok_comments = (
    {
      user_id =>  $comment->user_id,
      date_posted => $comment->date_posted,
      body => $comment->body
    }, 
    {
      user_id =>  $second_comment->user_id,
      date_posted => $second_comment->date_posted,
      body => $second_comment->body
    }
  );
```
```suggestion
  my @ok_comments = ({
      user_id =>  $comment->user_id,
      date_posted => $comment->date_posted,
      body => $comment->body
    }, {
      user_id =>  $second_comment->user_id,
      date_posted => $second_comment->date_posted,
      body => $second_comment->body
    });
```

2020-10-01 15:11 UTC, andreisamoila74 approved these changes

2020-10-01 20:26 UTC, S7012MY approved these changes

2020-10-01 20:32 UTC, merged