Refresh comments on add comment
S7012MY/CodeWell pull request #51
Opened 2020-10-05 18:17 UTC by dayanamdr

2020-10-06 09:24 UTC, andreisamoila74 requested changes

2020-10-06 09:24 UTC, andreisamoila74 commented on codewell-fe/src/Comment/Add.js
> +  const [onCommentChangeSuccess, setOnCommentChangeSuccess] = useState(0);
this should be actually be: onCommentAddSuccess

2020-10-06 09:24 UTC, andreisamoila74 commented on codewell-fe/src/Comment/View.js
> +  const [onCommentChangeSuccess, setOnCommentChangeSuccess] = useState([]);
same here

2020-10-07 19:41 UTC, S7012MY approved these changes

2020-10-07 20:22 UTC, andreisamoila74 approved these changes

2020-10-07 20:23 UTC, merged