User's codes feed BE
S7012MY/CodeWell pull request #58
Opened 2020-10-08 08:54 UTC by dayanamdr

2020-10-08 17:54 UTC, andreisamoila74 requested changes

2020-10-08 17:54 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE.pm
> +  $if_login->get('/api/code/feed/:username')->name('user_code_feed')
user_id instead of username

2020-10-08 17:54 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Code.pm
> +      validate_logged_in_user($self, $user_id) ||
this validation is useless because the route has already has $if_login condition on it

2020-10-08 17:54 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Code.pm
> +        validate_user_is_admin($self);
the name is not suggestive enough, which user?

2020-10-08 17:54 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Controller/Code.pm
> +  my $user_feed = $success ? get_user_code_feed($self, $user_id) : undef;
code_feed

2020-10-08 17:54 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Errors.pm
> +  invalid_username => 'User does not exist',
'User id does not exist. '

2020-10-09 11:23 UTC, andreisamoila74 requested changes

2020-10-09 11:23 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +  my($self, $user_id) = @_;
$self should be actually the controller here

2020-10-09 11:23 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Schema/ResultSet/Code.pm
> +  return $self->search({ author => $user_id });
```suggestion
 return shift->search({ author => pop });
```

2020-10-09 11:23 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +subtest 'Can view user code feed if the user is logged in' => sub {
which user can see the code feed? it's pretty ambiguous

2020-10-09 11:23 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +
the tests are good, but please name the subtest more suggestive

2020-10-09 13:34 UTC, S7012MY requested changes
You have duplicate code. You are already getting the feed and you could add something like by user and then have a function that transforms it into a map

2020-10-10 16:27 UTC, andreisamoila74 requested changes

2020-10-10 16:27 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +  my($controller, $user_id) = @_;
:(

2020-10-10 16:27 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +    }
this can be written on less lines

2020-10-10 16:27 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Schema/ResultSet/Code.pm
> +  return $self->search({ author => pop });
```suggestion
  return shift unless pop;
  return shift->search({ author => pop });
```
can't we write this function like this?

2020-10-10 16:27 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +subtest 'Admin user can request the code feed for all users' => sub {
this subtest is not so relevant, because you already check that an admin can view code feed for other user

2020-10-10 16:27 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +subtest 'Can not request the code feed for an inexistent user' => sub {
'view' would be a better word instead of 'request' in this case

2020-10-11 07:50 UTC, andreisamoila74 requested changes

2020-10-11 07:50 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +  # He gets redirected to his code feed instead.
'The user' instead of 'He'

2020-10-11 07:50 UTC, andreisamoila74 commented on codewellBe/t/Controller/code.t
> +subtest 'Non admin user can request his own code feed' => sub {
when I said 'view' instead of 'request', I meant in all of your new of subtest titles

2020-10-11 07:50 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +      ->ordered_by('date_posted', '-desc')->all ];
```suggestion
    shift->db->resultset('Code')->by_user_id(pop)
      ->ordered_by('date_posted', '-desc')->all ];
```

2020-10-11 07:50 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +  my ($controller, $user_id) = @_;
remove this

2020-10-11 07:50 UTC, andreisamoila74 commented on codewellBe/lib/codewellBE/Helper/Code.pm
> +      ->ordered_by('date_posted', '-desc')->all ];
more elegant this way

2020-10-11 13:06 UTC, andreisamoila74 approved these changes

2020-10-11 15:15 UTC, S7012MY approved these changes

2020-10-11 18:06 UTC, merged