User's codes feed FE
S7012MY/CodeWell pull request #59
Opened 2020-10-09 07:15 UTC by dayanamdr

2020-10-09 11:25 UTC, andreisamoila74 requested changes

2020-10-09 11:25 UTC, andreisamoila74 commented on codewell-fe/src/Code/UserFeed.js
> +  const listStyle = {
why do we need this?

2020-10-09 11:25 UTC, andreisamoila74 commented on codewell-fe/src/Code/UserFeed.js
> +  const pageStyle = {alignItems: 'center'};
```suggestion
  const pageStyle = { alignItems: 'center' };
```

2020-10-09 11:25 UTC, andreisamoila74 commented on codewell-fe/src/Code/UserFeed.js
> +      ? <PermissionsError error={error} />
you don't need to pass any error here

2020-10-14 19:21 UTC, andreisamoila74 requested changes
we don't need package-lock.json modified

2020-10-14 19:21 UTC, andreisamoila74 commented on codewell-fe/src/Code/Feed.js
> +  }
```suggestion
 userId = userId === undefined ? '' : userId;
```

2020-10-14 19:21 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Code/Feed.test.js
> +import React from 'react'
please don't remove ;

2020-10-14 19:21 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Code/Feed.test.js
> +import CodeFeed from '../../Code/Feed.js'
```suggestion
import CodeFeed from '../../Code/Feed.js';
```

2020-10-14 19:21 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Code/Feed.test.js
> +test('Render session user code feed if non admin user requests the code feed',
i don't understand this, can you explain please?

2020-10-15 09:44 UTC, andreisamoila74 approved these changes

2020-10-15 10:57 UTC, S7012MY requested changes

2020-10-15 10:57 UTC, S7012MY commented on codewell-fe/src/Code/Feed.js
> +    fetch('/api/code/feed?user_id=' + userId)
can we keep the back end consistent with the front end /feed/user_id?

2020-10-15 12:07 UTC, S7012MY approved these changes

2020-10-15 12:17 UTC, merged