Add comment reply FE
S7012MY/CodeWell pull request #63
Opened 2020-10-17 13:51 UTC by dayanamdr

2020-10-17 17:04 UTC, andreisamoila74 requested changes

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/Comment/View.js
> +    return showReplyBox[index] === 1? cancelButton : replyToButton;
:( 
```suggestion
    return showReplyBox[index] === 1 ? cancelButton : replyToButton;
```

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/Comment/View.js
> +  function children(index) {
children who?

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/Comment/View.js
>      <Layout style={pageStyle}>
indent this please, the whole code included in the <Layout />

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Comment/View.test.js
> +  const second_comment = comments[2].textContent;
you also have to check the new content, right?

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Comment/View.test.js
> +  expect(comments).toHaveLength(4);
same here and below

2020-10-17 17:04 UTC, andreisamoila74 commented on codewell-fe/src/Comment/View.js
> +  const [showReplyBox, setShowReplyBox] = useState([]);
why do we need both states?

2020-10-17 18:51 UTC, S7012MY requested changes
Please review your code again and name your variables in a right way

2020-10-17 18:51 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +import { List, Button, Layout, Comment } from 'antd';
let's put those in alphabetical order

2020-10-17 18:51 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  function onAddCommentReply(index) {
comentLine, we don't do snake_case in js

2020-10-17 18:51 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +    setReplyBox(addReply);
the naming here is not clear enough. I'd use something like isReplyBoxVisible

2020-10-18 10:37 UTC, S7012MY requested changes
Cancel button should be left of the post button in the post comment component

2020-10-18 10:37 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  function onAddCommentReply(commentLine) {
commentIndex

2020-10-18 10:37 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  const [isReplyBoxVisible, setIsReplyBoxVisible] = useState([]);
please add a comment explaining what this is used for

2020-10-18 10:37 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  const [isReplyButtonVisible, setIsReplyButtonVisible] = useState([]);
same here

2020-10-18 10:37 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  function button(commentLine) {
naming is bad

2020-10-18 17:58 UTC, S7012MY requested changes

2020-10-18 17:58 UTC, S7012MY commented on codewell-fe/src/Comment/Add.js
> +          {props.cancelButton}
I wouldn't pass a button as props, just the function for onCancel

2020-10-18 17:58 UTC, S7012MY commented on codewell-fe/src/Comment/Add.js
> +          {props.cancelButton}
Also the id should also be added

2020-10-18 17:58 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +  function onCancelCommentReply(commentIndex) {
onAdd and onCancel could be merged in the same function togleReplyBoxVisibility

2020-10-18 17:58 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +        Reply to
translation

2020-10-18 17:58 UTC, S7012MY commented on codewell-fe/src/Comment/View.js
> +                  datetime={comment.date_posted}
alphabetical order

2020-11-02 14:19 UTC, closed without merging