Add comments per lines FE
S7012MY/CodeWell pull request #64
Opened 2020-10-21 11:28 UTC by andreisamoila74

2020-10-22 12:30 UTC, S7012MY approved these changes

2020-10-22 12:41 UTC, S7012MY requested changes
write tests

2020-10-30 06:43 UTC, S7012MY requested changes
Comment box should dissappear after comment is posted. Also add tests for this behaviour

2020-10-30 06:43 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +  const [lineComments, setLineComments] = useState([]);
hasLineCommentBox

2020-10-30 06:43 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +                onClick={() => toggleLineCommentStatus(index + 1)} />
toggleHasLineComment

2020-10-30 06:43 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +                onClick={() => props.toggleLineCommentStatus(props.lineNumber)}>
don't forget about this line here

2020-11-10 11:57 UTC, S7012MY requested changes

2020-11-10 11:57 UTC, S7012MY commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +  // Should not display AddComment component on clicking plus button from line 1
this comment is not clear. Why shouldn't be that component shown if we click plus?

2020-11-10 11:57 UTC, S7012MY commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +function setUpDummyContainer() {
explain why do we need this

2020-11-10 17:45 UTC, S7012MY requested changes

2020-11-10 17:45 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +        props.updateComments();
are you sure that when we are doing this we won't lose any other textareas for comments on different lines? From my understanding this triggers a rerender for codeLines which resets its state.

2020-11-10 17:45 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +export function getCommentBodyId(lineNumber) {
why not getCommentTextareaId

2020-11-10 17:45 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +  return lineNumber ? `comment-body-code-line-${lineNumber}` : "comment-body";
comment-codeline-textarea-id

2020-11-10 17:45 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +  return lineNumber ? `comment-body-code-line-${lineNumber}` : "comment-body";
Why do we need "comment-body"?

2020-11-10 17:45 UTC, S7012MY commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +  // setup DOM element used as a dummy render target for a code line comment
comment before function in js

2020-11-10 19:49 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/Add.js
> +        props.updateComments();
yes, I am sure, because the state of the comment boxes will remain the same

2020-11-10 19:49 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +export function getCommentBodyId(lineNumber) {
you are right here, getCommentTextAreaId would be a better name, thanks for the suggestion

2020-11-10 19:50 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +  return lineNumber ? `comment-body-code-line-${lineNumber}` : "comment-body";
we need to have different ids for the comment bodies and post comments buttons in order to have well-done front-end tests

2020-11-10 19:50 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +  // setup DOM element used as a dummy render target for a code line comment
yep👍🏻

2020-11-11 13:38 UTC, S7012MY requested changes
You need to split the big test into smaller tests

2020-11-11 13:38 UTC, S7012MY commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +test('Toggle displaying add comment on line code', async () => {
after a specific line of the code

2020-11-11 13:38 UTC, S7012MY commented on codewell-fe/src/__tests__/Code/CodeTable.test.js
> +   * Click on the plus button icon from the code line 1 to display
shouldn't this be a separate test?

2020-11-11 20:37 UTC, S7012MY requested changes

2020-11-11 20:52 UTC, S7012MY approved these changes

2020-11-11 22:01 UTC, merged