Fix parent comment
S7012MY/CodeWell pull request #69
Opened 2020-10-23 13:11 UTC by AndreiTocu

2020-10-23 20:12 UTC, andreisamoila74 requested changes

2020-10-23 20:12 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    parent_comment_id => undef,
you don't need to include these fields here

2020-10-23 20:12 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
> +    parent_comment_id => undef,
they would be added by default with undef value in the db

2020-10-23 20:12 UTC, andreisamoila74 commented on codewellBe/t/Controller/comment.t
also test some comments with defined values for the new fields

2020-10-23 20:12 UTC, andreisamoila74 commented on codewellBe/t/lib/TestHelper.pm
>    $t->post_ok('/api/comment/add' => json => {
json => %comment_request

2020-10-24 20:50 UTC, andreisamoila74 requested changes
the pr is good, but please change the name of the commit in 'Fix code comments BE'

2020-10-25 15:23 UTC, S7012MY approved these changes

2020-10-25 18:14 UTC, andreisamoila74 approved these changes

2020-10-25 18:15 UTC, merged