Refactoring view code
S7012MY/CodeWell pull request #71
Opened 2020-10-23 19:43 UTC by andreisamoila74

2020-10-24 15:13 UTC, S7012MY requested changes
Add a comment for each component explaining where it's used at and what props it takes please

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/Code.js
> +function Code(props) {
this needs comments explaining what this component does and what props it takes
We should use a comment template for all the components so that we know what props each comment takes

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
>  function ViewCode() {
Eventually this component should be called Code

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/Code.js
> +function Code(props) {
A decent name would be CodeRows

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +    let viewCodePromise = getCode(id);
just do getCode(id).then()

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +  function updateComments() {
add a briefing explanation of this function and how it does trigger a rerender

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Card.js
> +import React from 'react';
let's name the file the same as the component

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    .then(response => response.json()).then(data => data);
you don't ned the last .then

2020-10-24 15:13 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +    .then(response => response.json()).then(data => data);
same here

2020-10-25 13:45 UTC, S7012MY requested changes
Are you 100% sure the tests are complete?

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +   - This component will receive as props the object code,
receives

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +/* - ViewCode component fetches data from the server and renders 2
fetches data from the server -> bad description
Where is this component used and what does it show?

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +/* - CodeTable is used in the parent component ViewCode.
first row just the name
Second row - renders the highlighted code in a table
It's used for showing the code part of the code review

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +   - CodeTable component will receive as props the code object to which it
this is off topic

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +   - CommentsList will receive as props an array with the comments for the code
same

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +/* - ViewCode component fetches data from the server and renders 2
You can say something like this is the base component for the code review. It fetches the code and the comments from the back end and passes them down to the children CodeTable and CommentsList

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CommentCard.js
> +  it's used in the parent component CommentsList.
it's used everywhere we want to display a comment

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CommentCard.js
> +   - It receives as props a comment object with the following keys:
Receives
  - object with the following props
    - p1
    - p2
Use the same template everywhere. 
By the way, there should be a template convention for javascript/react for documenting codee

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Comment/List.js
> +   - This component will receive as props an array with comments objects and a
stop writing essays 😂 Just do bullet points

2020-10-25 13:45 UTC, S7012MY commented on codewell-fe/src/Components/Comment/List.js
> +          updateComments={() => props.updateComments()}
are you sure what we need to have this inline function?

2020-10-25 14:36 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/List.js
> +          updateComments={() => props.updateComments()}
yes, I am sure

2020-10-25 14:44 UTC, andreisamoila74 reviewed
yes, tests are complete

2020-10-25 15:21 UTC, S7012MY requested changes

2020-10-25 15:21 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> + * CodeTable component
remove component

2020-10-25 15:21 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> + * • renders the highlighted code in a table
don't use bullet points, use dashes -

2020-10-25 15:21 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +     * Triggers in the child component CommentsList, after a valid comment
what gets triggered?

2020-10-25 15:21 UTC, S7012MY commented on codewell-fe/src/Components/Comment/List.js
> + *   • each comment object have the following keys
has

2020-10-25 15:21 UTC, S7012MY commented on codewell-fe/src/Components/Comment/List.js
> +          updateComments={() => props.updateComments()}
why?

2020-10-25 22:13 UTC, S7012MY requested changes

2020-10-25 22:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +    /**
comment before function definition

2020-10-25 22:13 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +    getCode(id).then(data => {
we don't need to get the code every time a comment is posted, so use a different effect which is called only once

2020-10-26 13:55 UTC, S7012MY approved these changes

2020-10-26 19:24 UTC, merged