Fix multiline highlight issue
S7012MY/CodeWell pull request #72
Opened 2020-10-28 13:36 UTC by alex0popa

2020-11-01 09:09 UTC, S7012MY requested changes
you also need to write tests

2020-11-01 09:09 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +  let beginOfLine = '';
beginOfLine  => linePrefix

2020-11-01 09:09 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    line = closeAllTheOpenedTags(line);
be consistent: line += closeAllOpenedTags

2020-11-01 09:09 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +function closeAllTheOpenedTags(line) {
closeOpenedTags

2020-11-01 09:09 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +      if (tag.indexOf(openTag) === 0) {
instead of searching for the whole string, you could just look for `/` and know you have a closed tag

2020-11-01 09:09 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +function closeAllTheOpenedTags(line) {
you could just add </span></span>... for the number of opened tags you had as a result in findTagsNotClosed so you don't need to iterate again over the whole line

2020-11-01 12:30 UTC, S7012MY requested changes
Donțt forget about tests

2020-11-01 12:30 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +export function multiLines(code) {
multiLineHighlight

2020-11-01 12:30 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    console.log(line);
remove

2020-11-01 12:30 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    linePrefix = addOpenedTags(tags);
getOpenedTags

2020-11-01 12:30 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    console.log(line);
remove

2020-11-01 12:30 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +// Highlight multi line
you need a btter comment here explaining what this function is needed for. You can explain that we need to split the code to multiple lines because we show every line in a tr

2020-11-02 13:06 UTC, S7012MY requested changes

2020-11-02 13:06 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +  let tags = [];
openTags

2020-11-02 13:06 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +  let linePrefix = [];
openTags

2020-11-02 13:06 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    line = getOpenedTags(linePrefix) + line;
get rid of getOpenedTags and use concat

2020-11-02 13:06 UTC, S7012MY commented on codewell-fe/src/Helpers/Code.js
> +    linePrefix = findTagsNotClosed(line);
findTagsNotClosed -> getOpenedTags

2020-11-02 17:05 UTC, S7012MY approved these changes

2020-11-02 19:26 UTC, andreisamoila74 approved these changes

2020-11-02 19:26 UTC, merged