Fix datetime issues
S7012MY/CodeWell pull request #77
Opened 2020-11-05 14:13 UTC by alex0popa

2020-11-05 14:32 UTC, andreisamoila74 approved these changes

2020-11-06 10:54 UTC, andreisamoila74 requested changes
using 'localstamp' is not solving your problem: https://metacpan.org/pod/Time::Stamp#localstamp -> you can read this

2020-11-08 12:28 UTC, S7012MY requested changes

2020-11-08 12:28 UTC, S7012MY commented on codewell-fe/src/Helpers/Utils.js
> +export function getDatePosted(utcDate) {
convertToLocalTimezone

2020-11-09 10:19 UTC, andreisamoila74 requested changes

2020-11-09 10:19 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Utils.js
> +// Convert utc date to local time zone date
```suggestion
// Convert UTC date to local time zone date
```

2020-11-09 10:19 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Utils.js
> +    'YYYY-MM-DD HH:mm:ss');
```suggestion
  let datePosted = moment.utc(utcDate).tz(timeZone)
    .format('YYYY-MM-DD HH:mm:ss');
```

2020-11-09 10:19 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Helpers/Utils.test.js
> +      '2020-01-01 13:00:00');
```suggestion
    expect(convertToLocalTimezone(utcDate))
      .toStrictEqual('2020-01-01 13:00:00');
```

2020-11-09 10:19 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Helpers/Utils.test.js
> +    expect(convertToLocalTimezone(utcDate)).toStrictEqual(
same here as above

2020-11-09 10:19 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/Helpers/Utils.test.js
> +    expect(convertToLocalTimezone(utcDate)).toStrictEqual(
same here as above

2020-11-09 11:43 UTC, andreisamoila74 approved these changes

2020-11-09 20:01 UTC, S7012MY approved these changes

2020-11-10 16:05 UTC, merged