Code lines comments
S7012MY/CodeWell pull request #79
Opened 2020-11-12 20:40 UTC by andreisamoila74

2020-11-13 09:44 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +  return commentsByLine;
comm

2020-11-13 09:44 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +  return commentsByLine;
f

2020-11-13 09:44 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +  return commentsByLine;
m

2020-11-14 13:15 UTC, S7012MY requested changes

2020-11-14 13:15 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +export function isCodeLineComment(comment) {
why do we need this function?

2020-11-14 13:15 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CommentCard.js
> +    {props.isCodeLineComment
code line comments should also have replies

2020-11-16 11:58 UTC, andreisamoila74 commented on codewell-fe/src/Helpers/Comment.js
> +export function isCodeLineComment(comment) {
take a look at the last function from this helper, I used this function as a filter

2020-11-16 12:26 UTC, S7012MY approved these changes

2020-11-16 15:34 UTC, merged