Error on failed login
S7012MY/CodeWell pull request #87
Opened 2020-11-19 20:18 UTC by alex0popa

2020-11-20 09:50 UTC, andreisamoila74 requested changes

2020-11-20 09:50 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/User/Login.test.js
> +test('Alert component displays an error if login fails', async () => {
I would integrate this test in the previous one because if login fails, onLoginSuccess isn't called and the alert is displayed, so basically is the same logic, and also we can avoid the repetitive code. @S7012MY what are your thoughts about this?

2020-11-20 09:50 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/User/Login.test.js
> +      json: () => Promise.resolve({succes: 0, error: 'Test error'})
```suggestion
      json: () => Promise.resolve({ succes: 0, error: 'Test error' })
```

2020-11-20 09:50 UTC, andreisamoila74 commented on codewell-fe/src/__tests__/User/Login.test.js
>  afterEach(() => {
why do we need to mount and unmount the container? I don't think is necessary for this test. please tell me if I am wrong

2020-11-20 11:16 UTC, S7012MY commented on codewell-fe/src/__tests__/User/Login.test.js
> +test('Alert component displays an error if login fails', async () => {
it seems that they are different tests, so it's fine how it is now

2020-11-20 13:10 UTC, alex0popa commented on codewell-fe/src/__tests__/User/Login.test.js
>  afterEach(() => {
I understand that it is a good practice: https://reactjs.org/docs/testing-recipes.html

2020-11-20 13:23 UTC, alex0popa commented on codewell-fe/src/__tests__/User/Login.test.js
>  afterEach(() => {
I read in the official documentation that it is a good practice, but here we do not use "container" in such a way that we need mount and unmount the container, you are right.

2020-11-20 16:33 UTC, S7012MY approved these changes

2020-11-21 21:36 UTC, andreisamoila74 approved these changes

2020-11-21 21:48 UTC, merged