Filter comments replies FE
S7012MY/CodeWell pull request #91
Opened 2020-11-27 11:39 UTC by dayanamdr

2020-12-04 20:28 UTC, andreisamoila74 requested changes

2020-12-04 20:28 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/Add.js
> +                className = "comment-form-button" onClick={onFormReset}>
```suggestion
                className="comment-form-button" onClick={onFormReset}>
```

2020-12-04 20:28 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> + *     - id - the id of the comments list used for unit testing the parent
is not relevant to include this

2020-12-04 20:28 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/List.js
> + *       - id - the id of the comments list used for unit testing the parent
same for this

2020-12-05 09:08 UTC, andreisamoila74 requested changes

2020-12-05 09:08 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> +      id={props.id}
here we can directly write "comments-list", and remove the id from the comment section, right?

2020-12-05 09:08 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/List.js
> + *       the ViewCode component after a comment is added successfully
make sure to include here all the parameters that come by props

2020-12-05 09:08 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> + *       the ViewCode component after a comment is added successfully
make sure to include all parameters that come by props in this comment

2020-12-05 09:08 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
>    const actions = [
also leave comments about actions and children, because it's difficult to get their role

2020-12-05 18:38 UTC, andreisamoila74 requested changes

2020-12-05 18:38 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> + *     - userId
```suggestion
 *     - userId - the id of the comment's author
```

2020-12-05 18:38 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> +   * Array with an action item rendered below the comment content
```suggestion
   * Array with an action item rendered below the comment body
```
```suggestion
   * Array with an action item rendered below the comment content
```

2020-12-05 18:38 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> +   * Array with children items rendered below the comment content
same here

2020-12-05 18:38 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> +  const children = [
you should also say why do we need action & children

2020-12-06 17:03 UTC, S7012MY requested changes
Waiting for the refactoring so that I'll be able to better review this

2020-12-06 17:03 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +        setCodeSectionComments(getCodeSectionComments(data.comments));
codeSectionComments? the naming tells me that this is the same as codeLines [the comments that are in the code section]

2020-12-21 18:27 UTC, S7012MY requested changes

2020-12-21 18:27 UTC, S7012MY commented on codewell-fe/src/Components/Code/View.js
> +        setComments(getCodeComments(data.comments));
getCodeComments isn't the best name. I suppose that this function is for filtering the comments that appear at the bottom of the page

2020-12-21 18:27 UTC, S7012MY commented on codewell-fe/src/Components/Comment/Add.js
> +        if (props.lineNumber || props.parentCommentId) {
we can have the same functionality as on github where after adding a comment you can add another one

2020-12-21 18:27 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CommentCard.js
> +    replyCommentBoxVisibility[props.commentIndex]
we don't render this conditionally because we moved the visibility inside AddComment

2020-12-21 18:27 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> +  for (let comment of comments.filter(comment => comment.line_number === null)) {
isn't filter already returning an array?

2020-12-21 18:27 UTC, S7012MY commented on codewell-fe/src/Helpers/Comment.js
> + * Receives an array containing comments objects and extracts in a new array
comments objects that belong to a code (or something like that)

2020-12-23 15:24 UTC, andreisamoila74 requested changes

2020-12-23 15:24 UTC, andreisamoila74 commented on codewell-fe/src/Components/Code/View.js
> +        // Filter the comments that belong to a code
"to the code" sounds better

2020-12-23 15:24 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CommentCard.js
> + *         comments and its replies
align this under the '-' on the line above. you can check the existing comments style in the project

2020-12-24 14:03 UTC, andreisamoila74 requested changes

2020-12-24 17:57 UTC, S7012MY approved these changes

2020-12-24 21:21 UTC, andreisamoila74 approved these changes

2020-12-24 21:22 UTC, merged