[WIP] Refactor CodeTable component
S7012MY/CodeWell pull request #92
Opened 2020-12-05 16:13 UTC by andreisamoila74

2020-12-06 17:28 UTC, S7012MY requested changes

2020-12-06 17:28 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +            codeLine={line}
change the name to code because that's what the variable contains

2020-12-06 17:28 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +            codeLineIndex={index}
index is enough

2020-12-06 17:28 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +            rowStyle={rowStyle}
why are we passing the css as props???

2020-12-06 17:28 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +            toggleLineCommentBoxVisibility={toggleLineCommentBoxVisibility}
why this here?

2020-12-06 18:25 UTC, S7012MY requested changes
I don't think for the Add comment component we need to pass the toggleLineCommentBox visibility. Isn't there a way where we pass a visible props to the component and then after posting we just do the logic inside the add component?

2020-12-06 18:25 UTC, S7012MY commented on codewell-fe/src/Components/Code/Line.js
> +        className={'language-' + props.codeLanguage} style={props.rowStyle}
why are we passing css? Also I don't think we need the class

2020-12-06 18:28 UTC, S7012MY requested changes

2020-12-06 18:28 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.codeLineComments
props shouldn't have the same name as the component

2020-12-06 18:28 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +              isCodeLineComment={1}
why do we need this?

2020-12-06 18:28 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.lineCommentBoxVisibility
would be great to move this logic in the AddComment component

2020-12-08 09:46 UTC, andreisamoila74 commented on codewell-fe/src/Components/Code/CodeTable.js
> +            rowStyle={rowStyle}
because we need rowStyle const in the CodeTable component, and also in the CodeLine component, so why defining the same parameter twice?

2020-12-08 09:46 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.codeLineComments
yep, you are right

2020-12-08 09:46 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +              isCodeLineComment={1}
because we don't have replies for the code line comments yet

2020-12-08 09:46 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.lineCommentBoxVisibility
I don't think this logic should be in the AddComment component, because the purpose of the AddComment component is to display the form for comment and doing the request for creating a comment, so moving this in the AddComment component, wouldn't break the component logic?

2020-12-08 13:39 UTC, S7012MY commented on codewell-fe/src/Components/Code/CodeTable.js
> +            rowStyle={rowStyle}
think about a different way for doing the same thing

2020-12-08 19:32 UTC, S7012MY requested changes

2020-12-08 19:32 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +              isCodeLineComment={1}
still why do we need this?
Also why don't we dirrectly use commentList?

2020-12-08 19:32 UTC, S7012MY commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.lineCommentBoxVisibility
because the logic for displaying it can be handled by AddComment. So the component decides when it should display anything or not

2020-12-09 09:18 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +              isCodeLineComment={1}
"still why do we need this?" -> in order to pass it to <CommentCard> component and renders the 'Reply to' button only if the isCodeLineComment is 0 
"Also why don't we dirrectly use commentList?" -> I don't understand what do you mean by this. to give up on the conditional rendering?

2020-12-09 09:18 UTC, andreisamoila74 commented on codewell-fe/src/Components/Comment/CodeLineComments.js
> +        {props.lineCommentBoxVisibility
👍🏻

2020-12-11 09:41 UTC, closed without merging